### ISSUE TITLE
Available for Chrome?

### ISSUE THREAD

**Issue by turkeyphant** [wijjo/passhash#12]
I see there's a chrome manifest but no mention of it in the readme?

**Comment by wijjo** [comment]
This is not under active development, but I believe there are one or two clones for Chrome done by other people. I'm a Chrome user myself, but no longer use or develop this extension.

**Comment by Barry1** [comment]
Hi,
I found out, that the [chrome extension PawHash](https://chrome.google.com/webstore/detail/pawhash/adgekjfphhgngpdoklolpjenmgneobfg) behaves compatible.
Maybe that helps for you.

**Comment by turkeyphant** [comment]
> I found out, that the chrome extension PawHash behaves compatible.

Amazing, thank you! I'll check it out :)
